version: "3.8"

services:
  web:
      build:
        context: .
        dockerfile: Dockerfile
      depends_on:
        - mysql
      environment:
        DB_USER: ${MYSQL_USER}
        DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        DB_HOST: mysql
        DB_NAME: ${MYSQL_DATABASE}
      ports:
        - 8000:8000
      volumes:
        - ./fastapi_templates:/app/fastapi_templates
      command: ["python", "-m", "poetry", "run", "uvicorn", "toodo.main:app", "--reload", "--proxy-headers", "--host", "0.0.0.0", "--port", "8000"]
      working_dir: /app

  mysql:
    image: mysql:8.1
    platform: linux/amd64
    container_name: mysql-container
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: ${TZ}

  migration:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./fastapi_templates:/app/fastapi_templates
    working_dir: /app/fastapi_templates/database
    command: ["python", "-m", "portry", "run", "alembic", "upgrade", "head"]
    depends_on:
      - mysql
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_HOST: mysql
      MYSQL_DATABASE: ${MYSQL_DATABASE}