version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql-dev
    environment:
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DB_HOST: mysql-dev
      DB_NAME: ${MYSQL_DATABASE}
    ports:
      - 8000:8000
    volumes:
      - ./fastapi_templates:/app/fastapi_templates
    command:
      [
        "python",
        "-m",
        "poetry",
        "run",
        "uvicorn",
        "fastapi_templates.main:app",
        "--reload",
        "--proxy-headers",
        "--host",
        "0.0.0.0",
        "--port",
        "8000"
      ]
    working_dir: /app

  mysql-dev:
    image: mysql:8.1
    platform: linux/amd64
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: ${TZ}

  migration:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./fastapi_templates:/app/fastapi_templates
    working_dir: /app/fastapi_templates/database
    command:
      [
        "python",
        "-m",
        "portry",
        "run",
        "alembic",
        "upgrade",
        "head"
      ]
    depends_on:
      - mysql-dev
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_HOST: mysql
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  tox:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/bash -c "python -m poetry add tox &&  python -m poetry run tox"
    environment:
      PYTHONUNBUFFERED: 1
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}-test
      DB_HOST: mysql-test
    ports:
      - "8001:8001"
    volumes:
      - ./tests:/app/tests
      - ./tox.ini:/app/tox.ini
      - ./fastapi_templates:/app/fastapi_templates
    depends_on:
      - mysql-test

  mysql-test:
    image: mysql:8.1
    platform: linux/amd64
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}-test
      TZ: ${TZ}
