version: '3.8'

services:
  web:
    command: /bin/bash -c "ls && python -m poetry add tox &&  python -m poetry run tox"
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8001:8001"
    volumes:
      - ./tests:/app/tests
      - ./tox.ini:/app/tox.ini

  mysql:
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE} # テスト用のDB名を変更
    ports:
      - "3307:3306"  # テスト用のDBポートを変更
